apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

resources:
  - ../../base

components:
  - ../../../components/vms/rhel9

generatorOptions:
  disableNameSuffixHash: true

# this results in deletion of the rootdisk volume[0]
patchesStrategicMerge:
  - patch-virtualmachine.yaml