apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base

# this results in deletion of the rootdisk volume[0]
patchesStrategicMerge:
  - patch-virtualmachine.yaml