apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: IPVLAN will assign the MAC of the 'master' interface
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-1924
  name: ipvlan-1924
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "ipvlan-1924", 
      "plugins": [{ 
        "type": "ipvlan",
        "master": "br-1924", 
        "mode": "l2",
        "ipam": {
          "type": "static",
          "addresses": [
            { "address": "192.168.4.213/24" }
            ]
            }
          },
          # without this next plugin get an address in use error
          {
        "type": "tuning",
        "capabilities": { "mac": true }
      }]
    }
