---
# oc process -p VLAN=1924 -p NODE_SELECTOR_KEY=kubernetes.io/hostname -p NODE_SELECTOR_VALUE=hub-q4jtr-cnv-dn79n \
#    -f templates/template-nncp.yaml -o yaml | yq e '.items[0]' - > nncp-hub-q4jtr-cnv-dn79n.yaml
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  annotations:
    description: Network Config for adding vlan 1924 1927 and bridge on ens224
  name: ens224-v1924-dn79n
spec:
  nodeSelector:
    kubernetes.io/hostname: hub-q4jtr-cnv-dn79n
  desiredState:
    interfaces:
      - name: ens224
        type: ethernet
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        state: up
      - name: ens224.1924
        type: vlan
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        state: up
        vlan:
          base-iface: ens224
          id: 1924
      - name: br-1924
        type: linux-bridge
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens224.1924
              vlan: {}
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        state: up

      - name: ens224.1927
        type: vlan
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        state: up
        vlan:
          base-iface: ens224
          id: 1927
      - name: br-1927
        type: linux-bridge
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens224.1927
              vlan: {}
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        state: up
