---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-mapping-1926
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - localnet: localnet-1926
          bridge: ovs-ens224
          state: present 