---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-mapping-1926
spec:
  nodeSelector:
    machine.openshift.io/cluster-api-machineset: hub-tq2sk-cnv
  desiredState:
    ovn:
      bridge-mappings:
        - localnet: vlan-1926
          bridge: br-vmdata
          state: present 