---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-1924
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1", 
      "name": "localnet-1924", 
      "type": "ovn-k8s-cni-overlay", 
      "topology": "localnet", 
      "netAttachDefName": "default/localnet-1924",
      "vlan": 1924,
      "ipam": {}
    }
