---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-vmdata-ovs
spec:
  nodeSelector:
    machine.openshift.io/cluster-api-machineset: hub-tq2sk-cnv
  desiredState:
    interfaces:
      - name: br-vmdata
        description: |-
          A dedicated OVS bridge with ens224 as a port
          allowing all VLANs and untagged traffic.
          Networks will be mapped to this brige via ovn.bridge-mappings in NNCPs
          associated with creation of those localnet networks.
        type: ovs-bridge
        state: up
        bridge:
          options:
            stp: true
          port:
            - name: ens224