---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configure Basics of Homelab network while optionally specifying node selector and NIC name.

resources:
  - ../../base

components:
  - ../../../demos/components/networks/vlan-1924/ovs-bridge
  - ../../../demos/components/networks/vlan-1926/ovs-bridge

patches:
  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: br-vmdata-ovs
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
          "nodeSelector": {
              "machine.openshift.io/cluster-api-machineset": "hub-tq2sk-cnv"
          }
        }
      - op: replace
        path: /spec/desiredState/interfaces/0/bridge/port/0/name
        value: ens224

  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: ovs-bridge-mapping-1924
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
          "nodeSelector": {
              "machine.openshift.io/cluster-api-machineset": "hub-tq2sk-cnv"
          }
        }

  - target:
      group: nmstate.io
      kind: NodeNetworkConfigurationPolicy
      name: ovs-bridge-mapping-1926
      version: v1
    patch: |-
      - op: replace
        path: /spec/nodeSelector
        value: {
          "nodeSelector": {
              "machine.openshift.io/cluster-api-machineset": "hub-tq2sk-cnv"
          }
        }