---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

resources:
  - ../../base

components:
  - ../../../components/vms/rhel9

patchesStrategicMerge:
  - patch-virtualmachine.yaml