---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

resources:
  - ../../base

components:
  - ../../../components/vms/rhel9

# the inline json patch can not learn of the random suffix
generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ignition-config
    files:
      - scripts/userData

# patchesStrategicMerge:
#   - patch-virtualmachine.yaml
patches:
- target:
    group: kubevirt.io
    kind: VirtualMachine
    name: rhel-node-1
    version: v1
  patch: |-
    - op: remove
      path: /spec/template/spec/volumes/1/cloudInitNoCloud

    - op: add
      path: /spec/template/spec/volumes/1/cloudInitConfigDrive
      value: {"secretRef":{"name":"ignition-config"}}

    - op: replace
      path: /spec/running
      value: true