---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

resources:
  - namespace.yaml
  - template-nad-vlan-cnv-bridge.yaml
  - template-nad-br-cnv-bridge-vlan.yaml
  - template-nncp-nic-vlan-br.yaml
  - template-nncp-nic-br.yaml
  - template-nncp-bond.yaml
