---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nncp

objects:
  - apiVersion: nmstate.io/v1
    kind: NodeNetworkConfigurationPolicy
    metadata:
      name: ${BOND}-${NIC1}-${NIC2}
      annotations:
        description: ${DESCRIPTION}
    spec:
      nodeSelector:
        ${NODE_SELECTOR_KEY}: ${NODE_SELECTOR_VALUE}
      desiredState:
        interfaces:

          # i think you need to up them to work
          - name: ${NIC1}
            type: ethernet
            state: up
            ipv4:
              enabled: false
            ipv6:
              enabled: false
          - name: ${NIC2}
            type: ethernet
            state: up
            ipv4:
              enabled: false
            ipv6:
              enabled: false

          - name: ${BOND}
            type: bond
            state: up
            ipv4:
              enabled: false
            ipv6:
              enabled: false
            link-aggregation:
              mode: 802.3ad
              port:
                - ${NIC1}
                - ${NIC2}

          - name: ${BOND}.${VLAN}
            type: vlan
            state: up
            vlan:
              base-iface: ${BOND}
              id: ${VLAN}
            ipv4:
              enabled: false
            ipv6:
              enabled: false
          - name: br-${VLAN}
            type: linux-bridge
            state: up
            bridge:
              options:
                stp:
                  enabled: false
              port:
                - name: ${BOND}.${VLAN}
                  vlan: {}
            ipv4:
              enabled: false
            ipv6:
              enabled: false

parameters:
  - description: Bond name
    name: BOND
    value: bond0
  - description: Physical NIC 1 to bond
    name: NIC1
    value: ens224
  - description: Physical NIC 2 to bond
    name: NIC2
    value: ens225
  - description: VLAN ID
    name: VLAN
  - description: Node Selector Key
    name: NODE_SELECTOR_KEY
    value: machine.openshift.io/cluster-api-machineset
  - description: Node Selector Value
    name: NODE_SELECTOR_VALUE
    value: hub-test-cnv
  - description: Policy description
    name: DESCRIPTION
    value: Network Config for adding bond and vlan ${VLAN} and bridge on ${NIC} 
