---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-virt

components:
  # this should have already been applied elsewhere
  - ../../demos/components/networks/br-vmdata/ovs-bridge

#  - ../../demos/components/multinetworkpolicy
#  - ../../demos/components/networks/vlan-1924/ovs-bridge
#  - ../../demos/components/networks/vlan-1926/ovs-bridge

