# oc process -f templates/template-nad-vlan-cnv-bridge.yaml \
#   -p VLAN=1924 \
#   -p DESCRIPTION="Lab Network 192.168.4.0/24 V1924" \
#   -o yaml | yq e '.items[0]'
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Lab Network 192.168.4.0/24 V1924
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-1924
  name: vlan-1924
  namespace: default
spec:
  config: |-
    {
      "bridge": "br-1924",
      "cniVersion": "0.3.1",
      "macspoofchk": true,
      "name": "vlan-1924",
      "type": "cnv-bridge",
      "vlan": 1924
    }